### ISSUE TITLE
Envelope list test fails on Jenkins

### ISSUE THREAD

**Issue by tpichlak** [carldata/borsuk#140]
It failed once on Jenkins but it passes locally. Maybe it's related to envelope model fitting time.
The error:

`should list the existing model *** FAILED ***
[info]   The code passed to eventually never returned normally. Attempted 15 times over 10.059967338999998 seconds. Last failure message: 0 was not equal to 1. (EnvelopeApiTest.scala:150)`

**Comment by wenta** [comment]
Is it still valid?

**Comment by tpichlak** [comment]
I don't think so. I am not sure but I think it was solved in some other issue.

**Comment by wenta** [comment]
So I will close this.
