### ISSUE TITLE
Rdii, why do we have childIds??

### ISSUE THREAD

**Issue by wenta** [carldata/borsuk#195]
When we return `RDIIObject` we return every time `childIds`. I think this is something what we can drop right now.
What do you think, @tpichlak @mjaniakcds

**Comment by mjaniakcds** [comment]
If I remember correctly, we do it because we use it in the list endpoint. You need to check if it is still used there and if not You can remove it.

**Comment by wenta** [comment]
We do not use it in list, so I will remove them.
