### ISSUE TITLE
Scaling Borsuk

### ISSUE THREAD

**Issue by klangner** [carldata/borsuk#74]
Function 'fit' will require lot of processing power and memory. 
It means that Borsuk will need to queue fit request and do them in background, so the webserwer will stay responsive.
This issue is for discussing possible solutions to this problem.

**Comment by wenta** [comment]
We would like to queue all fits between all modules (storms, prediction, rdii) or only in single module?

**Comment by klangner** [comment]
Probably all. Also I think it should be easier to implement generic queue instead of per model.
